
--Customers
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Wire Upon Receipt', 'Wire Upon Receipt', 0, 0, 0, '1001', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 20', 'NET 20', 20, 0, 0, '1002', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 30', 'NET 30', 30, 0, 0, '1003', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 45', 'NET 45', 45, 0, 0, '1004', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 60', 'NET 60', 60, 0, 0, '1005', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('3% 10 NET 30', '3% 10 NET 30', 30, 10, 3, '1007', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('2% 10 NET 30', '2% 10 NET 30', 30, 10, 2, '1008', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('2% 14 NET 30', '2% 14 NET 30', 30, 14, 2, '1014', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 1', 'NET 1', 1, 0, 0, 'Z1', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 2', 'NET 2', 2, 0, 0, 'Z10', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('2% 30 NET 60', '2% 30 NET 60', 60, 30, 2, 'Z11', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('3% 14 NET 30', '3% 14 NET 30', 30, 14, 3, 'Z12', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('2% 30 NET 90', '2% 30 NET 90', 90, 30, 2, 'Z13', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('3% 30 NET 90', '3% 30 NET 90', 90, 30, 3, 'Z14', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('2% NET 60', '2% NET 60', 60, 60, 2, 'Z15', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('2% 14 NET 60', '2% 14 NET 60', 60, 14, 2, 'Z16', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('2% 20 NET 30', '2% 20 NET 30', 30, 20, 2, 'Z17', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Payment Upon Receipt', 'Payment Upon Receipt', 0, 0, 0, 'Z18', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Pre-Paid', 'Pre-Paid', 0, 0, 0, 'Z19', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 90', 'NET 90', 90, 0, 0, 'Z2', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Pay Pal', 'Pay Pal', 0, 0, 0, 'Z20', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Pre-Paid by Wire', 'Pre-Paid by Wire', 0, 0, 0, 'Z21', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('COD Company Check', 'COD Company Check', 0, 0, 0, 'Z22', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Will Advise', 'Will Advise', 0, 0, 0, 'Z23', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('COD Cashiers Check', 'COD Cashiers Check', 0, 0, 0, 'Z24', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 90 End of Month', 'NET 90 End of Month', 90, 0, 0, 'Z25', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 60 End of Month', 'NET 60 End of Month', 60, 0, 0, 'Z26', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('50% Deposit 50% Pre-Paid', '50% Deposit 50% Pre-Paid', 0, 0, 0, 'Z27', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 1 Wire', 'NET 1 Wire', 1, 0, 0, 'Z28', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('50% Pre-Paid 50% NET 1', '50% Pre-Paid 50% NET 1', 1, 0, 0, 'Z29', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 120', 'NET 120', 120, 0, 0, 'Z3', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 30 End of Month', 'NET 30 End of Month', 30, 0, 0, 'Z30', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 15', 'NET 15', 15, 0, 0, 'Z4', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 5', 'NET 5', 5, 0, 0, 'Z5', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 7', 'NET 7', 7, 0, 0, 'Z6', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 3', 'NET 3', 3, 0, 0, 'Z7', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 10', 'NET 10', 10, 0, 0, 'Z8', 0, 4) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 75', 'NET 75', 75, 0, 0, 'Z9', 0, 4) 

--Vendors
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Payment upon Receipt', 'Payment upon Receipt', 0, 0, 0, '0001', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 7', 'NET 7', 7, 0, 0, '0002', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 30', 'NET 30', 30, 0, 0, '0004', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 1', 'NET 1', 1, 0, 0, 'Z100', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 45', 'NET 45', 45, 0, 0, 'Z101', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 60', 'NET 60', 60, 0, 0, 'Z102', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 15', 'NET 15', 15, 0, 0, 'Z103', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 5', 'NET 5', 5, 0, 0, 'Z104', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 25', 'NET 25', 25, 0, 0, 'Z105', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 30', 'NET 30', 30, 0, 0, 'Z106', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 10', 'NET 10', 10, 0, 0, 'Z107', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 2', 'NET 2', 2, 0, 0, 'Z108', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Pre-Paid', 'Pre-Paid', 0, 0, 0, 'Z109', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('NET 30 END OF MONTH', 'NET 30 END OF MONTH', 30, 0, 0, 'Z110', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('30% Deposit 70% Pre-Paid', '30% Deposit 70% Pre-Paid', 0, 0, 0, 'Z111', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('COD Company Check', 'COD Company Check', 0, 0, 0, 'Z112', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('70% Deposit 30% Pre-Paid', '70% Deposit 30% Pre-Paid', 0, 0, 0, 'Z113', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('20% Deposit 80% Pre-Paid', '20% Deposit 80% Pre-Paid', 0, 0, 0, 'Z114', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Pre-Paid by Wire', 'Pre-Paid by Wire', 0, 0, 0, 'Z115', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Will Advise', 'Will Advise', 0, 0, 0, 'Z116', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('COD Cashiers Check', 'COD Cashiers Check', 0, 0, 0, 'Z117', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('50% Deposit 50% Pre-Paid', '50% Deposit 50% Pre-Paid', 0, 0, 0, 'Z118', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Credit Card', 'Credit Card', 0, 0, 0, 'Z119', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Net 1 Wire', 'Net 1 Wire', 1, 0, 0, 'Z120', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Escrow', 'Escrow', 0, 0, 0, 'Z121', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('Wire upon Receipt', 'Wire upon Receipt', 0, 0, 0, 'Z122', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('10% Deposit 90% Pre-Paid', '10% Deposit 90% Pre-Paid', 0, 0, 0, 'Z123', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('50% Pre-Paid 50% Net 1', '50% Pre-Paid 50% Net 1', 1, 0, 0, 'Z124', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('25% Deposit 75% Pre-Paid', '25% Deposit 75% Pre-Paid', 0, 0, 0, 'Z125', 0, 1) 
INSERT INTO codes.lkpPaymentTerms (TermName, TermDesc, NetDueDays, DiscountDays, DiscountPercent, ExternalID, CreatedBy, AccountTypeID) VALUES ('30% Deposit 70% Net 1', '30% Deposit 70% Net 1', 1, 0, 0, 'Z126', 0, 1) 
