INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Tape & Reel', '101', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Tape & Box', '102', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Cut Tape', '107', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Digi-Reel', '106', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Tray', '103', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Tray - Waffle', '108', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Tube', '104', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Bulk', '105', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Each', '111', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Factory - Full', '109', 0)
INSERT INTO codes.lkpPackaging (PackagingName, ExternalID, CreatedBy) VALUES ('Factory - Partial', '110', 0)