INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('CIF - Cost, Insurance and Freight', 'CIF', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('CIP - Carriage and Insurance Paid To', 'CIP', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('CPT - Carriage Paid To', 'CPT', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('DAP - Delivered At Place', 'DAP', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('DDP - Delivered Duty Paid', 'DDP', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('DDU - Delivered Duty Unpaid', 'DDU', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('DES - Delivered Ex Ship', 'DES', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('EXW - Ex Works', 'EXW', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('FAS - Free Alongside', 'FCA', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('FCA - Free Carrier', 'FCA', 0)
INSERT INTO codes.lkpIncoterms (IncotermName, ExternalID, CreatedBy) VALUES ('FOB - Free On Board', 'FOB', 0)