INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (747860, 'BAKE ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (347412, 'CALIBRATION ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (643823, 'C-MODE SCAN. ACOUSTICAL MISCR. ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (723295, 'COPLANARITY ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (320774, 'CPU TESTING ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (678407, 'DECAPSULATION ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (722446, 'DESTRUCTIVE PHYSICAL ANALYSIS ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (981163, 'ELECTRICAL TEST ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (234568, 'FUNCTIONAL TEST ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (519106, 'FUNCTIONAL TESTING TO INDUSTRIAL SPECIFICATION ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (921680, 'HDD TESTING ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (398894, 'HIGH LEVEL ELECTRICAL TESTING ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (828185, 'LEAD STRAIGHTENING & COMBING ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (527103, 'PROGRAMMING & ERASE PROGRAMMING ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (511924, 'PTPR TEST ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (102485, 'REBALL BGA ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (588023, 'REMOVE PARTS FROM EXISTING REELS ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (241916, 'RE-TIN ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (132674, 'ROHS ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (945773, 'SOLDER TEST ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (508268, 'SOLDERABILITY TEST ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (945073, 'TAPE & REEL ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (388453, 'UPSCREEN PARTS FROM COMM TO IND OR EXT TEMP ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (386893, 'VISUAL INSPECTION / REMARK ', 'THIS IS THE DESCRIPTION', 0) 
INSERT INTO ItemExtras (ExternalID, ExtraName, ExtraDescription, CreatedBy) VALUES (495743, 'WIPE/TEST/HD ', 'THIS IS THE DESCRIPTION', 0) 
