INSERT INTO lkpAccountStatuses ([Name], AccountIsMgmtApproved, AccountIsFinanceApproved, AccountIsActive, AccountIsBlacklisted, ExternalID, IsDefault, CreatedBy)
VALUES ('Prospect', 0, 0, 1, 0, 'Item1', 1, 0)
INSERT INTO lkpAccountStatuses ([Name], AccountIsMgmtApproved, AccountIsFinanceApproved, AccountIsActive, AccountIsBlacklisted, ExternalID, IsDefault, CreatedBy)
VALUES ('No Potential', 0, 0, 0, 0, NULL, 0, 0)
INSERT INTO lkpAccountStatuses ([Name], AccountIsMgmtApproved, AccountIsFinanceApproved, AccountIsActive, AccountIsBlacklisted, ExternalID, IsDefault, CreatedBy)
VALUES ('Active', 1, 1, 1, 0, 'Item2', 0, 0)
INSERT INTO lkpAccountStatuses ([Name], AccountIsMgmtApproved, AccountIsFinanceApproved, AccountIsActive, AccountIsBlacklisted, ExternalID, IsDefault, CreatedBy)
VALUES ('Locked', 0, 0, 1, 0, NULL, 0, 0)
INSERT INTO lkpAccountStatuses ([Name], AccountIsMgmtApproved, AccountIsFinanceApproved, AccountIsActive, AccountIsBlacklisted, ExternalID, IsDefault, CreatedBy)
VALUES ('Blacklisted', 0, 0, 0, 0, 'Item3', 0, 0)
INSERT INTO lkpAccountStatuses ([Name], AccountIsMgmtApproved, AccountIsFinanceApproved, AccountIsActive, AccountIsBlacklisted, ExternalID, IsDefault, CreatedBy)
VALUES ('Archived', 0, 0, 0, 0, 'Item4', 0, 0)
