INSERT INTO lkpCurrencies (CurrencyID, CurrencyName, ExternalID, CreatedBy) VALUES ('USD', 'US Dollar', 'USD', 0)
INSERT INTO lkpCurrencies (CurrencyID, CurrencyName, ExternalID, CreatedBy) VALUES ('EUR', 'Euro', 'EUR', 0)
INSERT INTO lkpCurrencies (CurrencyID, CurrencyName, ExternalID, CreatedBy) VALUES ('SGD', 'Singapore Dollar', 'SGD', 0)
INSERT INTO lkpCurrencies (CurrencyID, CurrencyName, ExternalID, CreatedBy) VALUES ('HKD', 'Hong Kong Dollar', 'HKD', 0)
INSERT INTO lkpCurrencies (CurrencyID, CurrencyName, ExternalID, CreatedBy) VALUES ('CNY', 'Yuan Renminbi', 'CNY', 0)
INSERT INTO lkpCurrencies (CurrencyID, CurrencyName, ExternalID, CreatedBy) VALUES ('MXN', 'Mexican Peso', 'MXN', 0)