INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Customer', 'Select', 'Quotes.AccountID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Contact', 'Select', 'Quotes.ContactID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Project', 'Select', 'Quotes.ProjectID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Status', 'Select', 'Quotes.StatusID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Incoterms', 'Select', 'Quotes.IncotermID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Payment Terms', 'Select', 'Quotes.PaymentTermID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Currency', 'Select', 'Quotes.CurrencyID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Ship To', 'Select', 'Quotes.ShipLocationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Organization', 'Select', 'Quotes.OrganizationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Send Date', 'Date', 'Quotes.SentDate', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Valid For', 'Number', 'Quotes.ValidForHours', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Customer', 'Select', 'SalesOrders.AccountID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Contact', 'Select', 'SalesOrders.ContactID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Project', 'Select', 'SalesOrders.ProjectID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Status', 'Select', 'SalesOrders.StatusID', 0) 
INSERT INTO lkpFields (NavID, FieldName, FieldType, ObjectTypeID, DataLocation, CreatedBy) VALUES (14, 'Delivery Rule', 'Select', 16, 'SalesOrders.DeliveryRuleID', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Incoterms', 'Select', 'SalesOrders.IncotermID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Payment Terms', 'Select', 'SalesOrders.PaymentTermID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Currency', 'Select', 'SalesOrders.CurrencyID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Ship To', 'Select', 'SalesOrders.ShipLocationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Organization', 'Select', 'SalesOrders.OrganizationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Ultimate Destination', 'Select', 'SalesOrders.UltDestinationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Freight Payment', 'Select', 'SalesOrders.FreightPaymentID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Order Date', 'Date', 'SalesOrders.OrderDate', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Customer PO', 'Text', 'SalesOrders.CustomerPO', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'Freight Account', 'Text', 'SalesOrders.FreightAccount', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Vendor', 'Select', 'PurchaseOrders.AccountID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Vendor Rating', 'Label', 'TBD', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Contact', 'Select', 'PurchaseOrders.ContactID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Status', 'Select', 'PurchaseOrders.StatusID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Ship From', 'Select', 'PurchaseOrders.FromLocationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Ship To', 'Select', 'PurchaseOrders.ToWarehouseID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Incoterms', 'Select', 'PurchaseOrders.IncotermID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Payment Terms', 'Select', 'PurchaseOrders.PaymentTermID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Currency', 'Select', 'PurchaseOrders.CurrencyID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Organization', 'Select', 'PurchaseOrders.OrganizationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (22, 18, 'Order Date', 'Date', 'PurchaseOrders.OrderDate', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Company Type', 'Select', 'Accounts.CompanyTypeID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Parent Account', 'Select', 'Accounts.ParentAccountID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Organization', 'Select', 'Accounts.OrganizationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Status', 'Select', 'Accounts.AccountStatusID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Currency', 'Select', 'Accounts.CurrencyID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Account Types', 'Checkboxes', 'Accounts.AccountTypeID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Name', 'Text', 'Accounts.AccountName', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Email', 'Text', 'Accounts.Email', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Website', 'Text', 'Accounts.Website', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Year Established', 'Date', 'Accounts.YearEstablished', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'NumOfEmployees', 'Number', 'Accounts.NumOfEmployees', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'ProductFocus', 'Select', 'Accounts.EndProductFocus', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'CarryStock', 'Select', 'Accounts.CarryStock', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'MinimumPO', 'Number', 'Accounts.MinimumPO', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'ShippingInstructions', 'Text', 'Accounts.ShippingInstructions', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'VendorNum', 'Text', 'Accounts.VendorNum', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'SupplierRating', 'Label', 'Accounts.SupplierRating', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Account Number', 'Label', 'Accounts.AccountNum', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Parent Company', 'Select', '', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Region', 'Select', 'Accounts.AccountHierarchyID', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Credit Limit', 'Label', 'Accounts.CreditLimit', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Open Balance', 'Label', 'Accounts.OpenBalance', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Approved Vendor', 'Checkbox', 'Accounts.ApprovedVendor', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Status', 'Select', 'Contacts.ContactStatusID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'IsActive', 'Checkbox', 'Contacts.IsActive', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Note', 'Text', 'Contacts.Details', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Department', 'Text', 'Contacts.Department', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Job Function', 'Select', 'Contacts.JobFunctionID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Birthdate', 'Date', 'Contacts.Birthdate', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Gender', 'Select', 'Contacts.Gender', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Salutation', 'Select', 'Contacts.Salutation', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Marital Status', 'Select', 'Contacts.MaritalStatus', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Kids Names', 'Text', 'Contacts.KidsNames', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Reports To', 'Text', 'Contacts.ReportsTo', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'First Name', 'Text', 'Contacts.FirstName', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Last Name', 'Text', 'Contacts.LastName', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Title', 'Text', 'Contacts.Title', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Shipping Location', 'Select', 'Contacts.LocationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Office Phone', 'Text', 'Contacts.OfficePhone', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Mobile Phone', 'Text', 'Contacts.MobilePhone', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Fax', 'Text', 'Contacts.Fax', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Email', 'Text', 'Contacts.Email', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (2, 5, 'Preferred', 'Select', 'Contacts.PreferredContactMethodID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'MPN', 'Text', 'Items.PartNumber', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Manufacturer', 'Select', 'Items.MfrID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Status', 'Select', 'Items.ItemStatusID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Group', 'Select', 'Items.CommodityID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Commodity', 'Select', 'Items.CommodityID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Description', 'Text', 'Items.PartDescription', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'EU RoHS', 'Select', 'Items.EURoHS', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'CN RoHS', 'Select', 'Items.CNRoHS', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'ECCN', 'Text', 'Items.ECCN', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'HTS', 'Text', 'Items.HTS', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'MSL', 'Number', 'Items.MSL', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Length', 'Number', 'Items.LengthCM', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Width', 'Number', 'Items.WidthCM', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Depth', 'Number', 'Items.DepthCM', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (103, 28, 'Weight', 'Number', 'Items.WeightG', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (27, 31, 'Supplier', 'Int', 'VendorRFQs.AccountID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (27, 31, 'Contact', 'Int', 'VendorRFQs.ContactID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (27, 31, 'Status', 'Int', 'VendorRFQs.StatusID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (27, 31, 'Organization', 'Int', 'VendorRFQs.OrganizationID', 0) 
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (27, 31, 'Currency', 'Int', 'VendorRFQs.CurrencyID', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'Approved Vendor', 'Checkbox', 'Accounts.ApprovedVendor', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'PONotes', 'Text', 'Accounts.PONotes', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (1, 4, 'QCNotes', 'Text', 'Accounts.QCNotes', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'QCNotes', 'Text', 'SalesOrders.QCNotes', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (16, 14, 'ShippingNotes', 'Text', 'SalesOrders.ShippingNotes', 0)
INSERT INTO lkpFields (ObjectTypeID, NavID, FieldName, FieldType, DataLocation, CreatedBy) VALUES (19, 7, 'Quote Type', 'Select', 'Quotes.QuoteTypeID', 0)
INSERT INTO lkpFields (NavID, FieldName, FieldType, ObjectTypeID, DataLocation, CreatedBy) VALUES (14, 'Carrier Method', 'Select', 16, 'SalesOrders.ShipMethod', 3);