--IHS
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'ACF', 'Active Filters', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'REG', 'Regulators', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'OTR', 'Other Semiconductors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'CVT', 'Converters', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'TIC', 'Telecom ICs', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'LIC', 'Logic ICs', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'CAP', 'Capacitors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'RES', 'Resistors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'CNS', 'Connector Support', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'CIC', 'Consumer ICs', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'TRN', 'Transformers', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'CCN', 'Circular Connectors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'BAT', 'Batteries', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'PER', 'uPs/uCs/Peripheral ICs', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'TRG', 'Trigger Devices', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'DIO', 'Diodes', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'AMP', 'Amplifiers', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'IIC', 'Interface ICs', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'PFL', 'Passive Filters', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'OSC', 'Oscillators', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'CRY', 'Crystals/Resonators', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'CPT', 'Circuit Protection Devices', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'RTC', 'Rectangular Connectors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'BCN', 'Board Connectors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (4, 'SWI', 'Switches', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'OPT', 'Optoelectronics', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'MIC', 'Memory ICs', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'TSD', 'Thermal Support Devices', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'FCN', 'Fiber Optic Connectors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'FOP', 'Fiber Optics', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'PLG', 'Programmable Logic ICs', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'IND', 'Inductors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'SEN', 'Sensors/Transducers', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'TRA', 'Transistors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (1, 'RFM', 'RF/Microwave Devices', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'OIN', 'Other Interconnects', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (4, 'REL', 'Relays', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'RCN', 'RF Connectors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (2, 'PNR', 'Passive Networks', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'SCC', 'Sockets and Chip Carriers', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'TCN', 'Telecom and Datacom Connectors', 0) 
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (3, 'TRM', 'Terminals and Terminal Blocks', 0)

--Non IHS
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'CPU', 'CPU Processors', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'HDD', 'Hard Disk Drives', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'HRD', 'Hardware/Screws/Grommets/Pins', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'LCD', 'Liquid Crystal Displays', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'MC',  'Memory Cards SD/CF/MMC/XD', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'MMD', 'DDR Based Memory Modules', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'MOT', 'Motherboard Based Peripherals', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'SSD', 'Solid State Drives', 0)
INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'TFT', 'TFT Panels', 0)

INSERT INTO lkpItemCommodities (ItemGroupID, ExternalID, CommodityName, CreatedBy) VALUES (5, 'MIS', 'Miscellaneous/Unknown', 0)