
SET IDENTITY_INSERT lkpNavigation ON;
INSERT INTO lkpNavigation 
(NavID, ParentNavID, Interface,							NavName,					Icon,				SortOrder, IsNavMenu, CreatedBy) VALUES 
  (1,	NULL,	'pages/dashboard',						'Dashboard',				'fa-tachometer',	1,	1,	0) 
--, (2, NULL,	'pages/accounts',						'Accounts',					'fa-vcard-o',		2,	1,	0) 
, (40,	NULL,	'pages/accounts/customers',				'Customers',				'fa-vcard-o',		2,	1,	0) 
, (41,	NULL,	'pages/accounts/suppliers',				'Vendors',					'fa-vcard-o',		2,	1,	0) 
, (3,	NULL,	'NewAccount',							'New Account',				'',					0,	0,	0) 
, (4,	NULL,	'AccountDetails',						'Account Details',			'',					0,	0,	0) 
, (5,	NULL,	'ContactDetails',						'Contact Details',			'',					0,	0,	0) 
, (6,	NULL,	'pages/quotes',							'Quotes',					'fa-file-text-o',	3,	1,	0) 
, (7,	6,		'QuoteBasicDetails',					'Quote Details',			'',					0,	0,	0) 
, (8,	6,		'QuoteParts',							'Quote Parts',				'',					0,	0,	0) 
, (9,	6,		'QuoteExtraitems',						'Quote Extras',				'',					0,	0,	0) 
, (10,	NULL,	'OwnershipAssignment',					'Ownership Assignment',		'',					0,	0,	0) 
, (11,	NULL,	'pages/sourcing',						'Sourcing',					'fa-exchange',		4,	1,	0) 
, (12,	NULL,	'PartSources',							'Sources Component',		'',					0,	0,	0) 
, (13,	NULL,	'pages/sales-orders',					'Sales Orders',				'fa-money',			5,	1,	0) 
, (14,	13,		'SalesOrdersBasicDetails',				'Sales Order Details',		'',					0,	0,	0) 
, (15,	13,		'SalesOrdersParts',						'Sales Order Lines',		'',					0,	0,	0) 
, (16,	13,		'SalesOrdersExtra',						'Sales Order Extras',		'',					0,	0,	0) 
, (17,	NULL,	'pages/purchase-orders',				'Purchase Orders',			'fa-shopping-cart', 6,	1,	0) 
, (18,	17,		'PurchaseOrderBasicDetails',			'Purchase Order Details',	'',					0,	0,	0) 
, (19,	17,		'PurchaseOrdersParts',					'Purchase Order Parts',		'',					0,	0,	0) 
, (20,	17,		'PurchaseOrdersExtra',					'Purchase Order Extras',	'',					0,	0,	0) 
, (21,	NULL,	'pages/order-fulfillment',				'Order Fulfillment',		'fa-tasks',			7,	1,	0) 
, (22,	NULL,	'',										'Quality Control',			'fa-check-square-o', 8, 1,	0) 
, (23,	22,		'pages/quality-control/inspections',	'Inspections',				'',					9,	1,	0) 
, (24,	22,		'pages/quality-control/checklist',		'Checklists',				'',					10,	1,	0) 
, (25,	NULL,	'',										'Parts Lookup',				'fa-search',		11,	1,	0) 
, (26,	25,		'pages/bom/search',						'History',					'fa-search',		12,	1,	0) 
, (27,	NULL,	'BomSearch',							'BOM Search',				'',					0,	0,	0) 
, (28,	25,		'pages/items',							'Parts',					'fa-microchip',		13, 1,	0) 
, (29,	25,		'pages/bom/lists',						'Lists',					'fa-list-ol',		14, 1,	0) 
, (30,	NULL,	'pages/rfqs',							'Vendor RFQs',				'fa-hdd-o',			15, 1,	0) 
, (31,	30,		'RFQBasicDetails',						'RFQ Details',				'',					0,	0,	0) 
, (32,	30,		'RfqLines',								'RFQ Lines',				'',					0,	0,	0) 
, (33,	30,		'RfqResponses',							'RFQ Responses',			'',					0,	0,	0) 
, (34,	NULL,	'',										'Admin',					'fa-cog',			16, 1,	0) 
, (35,	34,		'pages/users',							'Users',					'',					17, 1,	0) 
, (36,	34,		'pages/roles',							'Roles',					'',					18, 1,	0) 
, (37,	34,		'pages/error-monitor',					'Error Monitor',			'',					19, 1,	0) 
, (38,	34,		'pages/workflow-management',			'Workflow Management',		'',					20, 1,	0)
, (42,	NULL,	'pages/request-to-purchase',			'Request To Purchase',		'fa-cart-plus',		5,	1,	0)
, (43,	34,		'pages/Transactions',					'Transactions',				'',					21,	1,	3)
SET IDENTITY_INSERT lkpNavigation OFF;