INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Accounts Owned by (User)', 1, 1, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Contacts Owned By (User)', 1, 2, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Region', 1, 3, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Hierarchy', 1, 4, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All or Specific Account', 1, 1, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Contacts Owned By (User)', 2, 2, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Accounts Owned by (User)', 2, 1, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Region', 2, 3, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Hierarchy', 2, 4, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Accessible Accounts', 2, 1, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All Contacts', 2, 2, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Item Lists Owned By (User)', 25, 25, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Accounts Owned by (User)', 25, 1, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Contacts Owned By (User)', 25, 2, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Region', 25, 3, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Hierarchy', 25, 4, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Accessible Accounts', 25, 1, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All Item Lists', 25, 25, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Quotes Owned By (User)', 19, 19, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Accounts Owned by (User)', 19, 1, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Contacts Owned By (User)', 19, 2, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Region', 19, 3, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Hierarchy', 19, 4, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Accessible Accounts', 19, 1, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All Quotes', 19, 19, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Sales Orders Owned By (User)', 16, 16, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Accounts Owned by (User)', 16, 1, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('Contacts Owned By (User)', 16, 2, 1, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Region', 16, 3, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Hierarchy', 16, 4, 3, 0, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('In Accessible Accounts', 16, 1, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All Sales Orders', 16, 16, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All Vendor RFQs', 27, 27, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All Purchase Orders', 22, 22, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All Items', 103, 103, 3, 1, 0) 
INSERT INTO lkpObjectTypeSecurity (TypeDescription, ObjectTypeID, FilterObjectTypeID, FilterTypeID, IsForAllObjects, CreatedBy) VALUES ('All QC Inspections', 104, 104, 3, 1, 0) 