INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanCreate', 'Create a new quote', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanEmail', 'Email the quote to customer', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanExport', 'Download excel export of quote or quote grid', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanPrint', 'Print a PDF of the quote', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanEditLines', 'Modify line items on a quote', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanViewLines', 'See line items on a quote', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanLinkSources', 'Link Sources to line items on a quote', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanEditExtras', 'Modify extras on a quote', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (19, 'CanViewExtras', 'View extras on a quote', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (106, 'CanCreate', 'Create a new source', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (106, 'CanExport', 'Download excel export of sources', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanCreate', 'Create a new sales order from a quote', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanEditOwnership', 'Modify ownership of a sales order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanEmail', 'Email the sales order to a customer', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanExport', 'Download excel export of sales order or SO grid', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanPrint', 'Print a PDF of the sales order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanEditLines', 'Modify line items on a sales order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanViewLines', 'See line items on a sales order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanFulfill', 'Commit inventory or PO quantity to a sales order', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanEditExtras', 'Modify extras on a sales order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (16, 'CanViewExtras', 'View extras on a sales order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanCreate', 'Create a new purchase order', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanEditOwnership', 'Modify ownership of a purchase order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanEmail', 'Email the purchase order to a supplier', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanExport', 'Download excel export of purchase order or PO grid', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanPrint', 'Print a PDF of the purchase order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanEditLines', 'Modify line items on a purchase order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanViewLines', 'See line items on a purchase order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanEditExtras', 'Modify extras on a purchase order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (22, 'CanViewExtras', 'View extras on a purchase order', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (1, 'CanCreate', 'Create a new account', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (1, 'CanEditOwnership', 'Modify ownership of an account', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (1, 'CanExport', 'Download excel export of the account or account grid', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (2, 'CanCreate', 'Create a new contact', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (2, 'CanEditOwnership', 'Modify ownership of a contact', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (2, 'CanExport', 'Download excel export of the contact or contact grid', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (103, 'CanCreate', 'Create a new part number', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (102, 'CanCreate', 'Create a new manufacturer', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (27, 'CanCreate', 'Create a new vendor RFQ', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (27, 'CanView', 'View vendor RFQs', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (27, 'CanEdit', 'Modify lines on a vendor RFQ', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (27, 'CanExport', 'Download an excel export of an RFQ or the RFQ grid', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (104, 'CanCreate', 'Create a new QC Inspection', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (104, 'CanView', 'View QC inspections', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (104, 'CanEdit', 'Edit QC inspections', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (104, 'CanExport', 'Download an excel export of the QC Inspection or grid', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (32, 'CanCreate', 'Create a new user', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (25, 'CanCreateBOM', 'Create an item list by uploading an Excel document', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (25, 'CanCreateOffers', 'Create an outside offer list by uploading Excel', 0, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (2, 'CanEditProjects', 'Modify the Projects a contact works with', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (2, 'CanEditFocus', 'Modify the line card the contact specializes in', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (1, 'CanEditProjects', 'Modify the Projects an Account has', 1, 0) 
INSERT INTO lkpPermissions (ObjectTypeID, PermName, PermDescription, IsObjectSpecific, CreatedBy) VALUES (1, 'CanEditFocus', 'Modify the line card for the Account', 1, 0) 
