INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines', 'PartNumber', 'Part Number', 'nvarchar', 1, 1) 
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines', 'Manufacturer', 'Manufacturer', 'nvarchar', 1, 1) 
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines', 'CustomerPartNum', 'Int Part #', 'nvarchar', 0, 1) 
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines', 'Qty', 'Qty', 'int', 0, 1) 
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines', 'TargetPrice', 'Target Price', 'money', 0, 1) 
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines', 'TargetDateCode', 'Target DC', 'nvarchar', 0, 1) 
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines', 'AssocAccountID', 'OEM', 'nvarchar', 0, 1) 
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','PartNumber','Part Number','nvarchar', 1, 2)
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','Manufacturer','Manufacturer','nvarchar', 1, 2)
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','CustomerPartNum','Int Part #','nvarchar', 0, 2)
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','Qty','Qty','int', 0, 2)
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','Cost','Cost','money', 0, 2)
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','DateCode','TargetDateCode','nvarchar', 1, 2)
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','MOQ','MOQ','nvarchar', 0, 2)
INSERT INTO lkpXlsDataMap (XlsType, ColumnName, FieldLabel, DataType, IsRequired, ItemListTypeID) VALUES ('ItemListLines','MOQ','SPQ','nvarchar', 0, 2)