CREATE TABLE [dbo].[Accounts] (
    [AccountID]            INT           IDENTITY (1, 1) NOT NULL,
    [CompanyTypeID]        INT           NULL,
    [AccountHierarchyID]   INT           NULL,
    [OrganizationID]       INT           NULL,
    [CurrencyID]           CHAR (3)      NULL,
    [AccountName]          VARCHAR (128) NULL,
    [AccountNum]           VARCHAR (128) NULL,
    [IsSourceability]      BIT           CONSTRAINT [DF_Accounts_IsSourceability] DEFAULT ((0)) NOT NULL,
    [ExternalID]           VARCHAR (50)  NULL,
    [Created]              DATETIME      CONSTRAINT [DF__Accounts__Create__546180uu] DEFAULT (getutcdate()) NULL,
    [CreatedBy]            INT           NULL,
    [Modified]             DATETIME      NULL,
    [ModifiedBy]           INT           NULL,
    [IsDeleted]            BIT           CONSTRAINT [DF__Accounts__IsDele__5555Ag5] DEFAULT ((0)) NULL,
    [CreditLimit]          MONEY         NULL,
    [OpenBalance]          MONEY         NULL,
    [Email]                VARCHAR (250) NULL,
    [Website]              VARCHAR (MAX) NULL,
    [YearEstablished]      DATE          NULL,
    [NumOfEmployees]       INT           NULL,
    [EndProductFocus]      VARCHAR (250) NULL,
    [CarryStock]           BIT           NULL,
    [MinimumPO]            MONEY         NULL,
    [ShippingInstructions] VARCHAR (MAX) NULL,
    [VendorNum]            VARCHAR (50)  NULL,
    [SupplierRating]       VARCHAR (50)  NULL,
    [QCNotes]              VARCHAR (MAX) NULL,
    [PONotes]              VARCHAR (MAX) NULL,
    [ApprovedVendor]       BIT           DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK__Accounts__349DA586463BC6BF] PRIMARY KEY CLUSTERED ([AccountID] ASC)
);

