CREATE TABLE [dbo].[QuoteLines] (
    [QuoteLineID]      INT            IDENTITY (1, 1) NOT NULL,
    [QuoteID]          INT            NOT NULL,
    [QuoteVersionID]   INT            NOT NULL,
    [ItemListLineID]   INT            NULL,
    [StatusID]         INT            NOT NULL,
    [ItemID]           INT            NULL,
    [CommodityID]      INT            NOT NULL,
    [AltFor]           INT            NULL,
    [LineNum]          INT            NOT NULL,
    [CustomerLine]     INT            NULL,
    [CustomerPartNum]  NVARCHAR (32)  NULL,
    [PartNumber]       NVARCHAR (32)  NOT NULL,
    [PartNumberStrip]  NVARCHAR (32)  NOT NULL,
    [Manufacturer]     NVARCHAR (128) NOT NULL,
    [Qty]              INT            NOT NULL,
    [TargetPrice]      MONEY          NULL,
    [Price]            DECIMAL (9, 3) NOT NULL,
    [Cost]             MONEY          NOT NULL,
    [TargetDateCode]   NVARCHAR (25)  NULL,
    [DateCode]         NVARCHAR (25)  NULL,
    [PackagingID]      INT            NULL,
    [ShipDate]         DATE           NULL,
    [DueDate]          DATE           NULL,
    [IsRoutedToBuyers] BIT            CONSTRAINT [DF__QuoteLine__IsRou__7A8729A3] DEFAULT ((0)) NOT NULL,
    [Created]          DATETIME       CONSTRAINT [DF__QuoteLine__Creat__7B7B4DDC] DEFAULT (getutcdate()) NOT NULL,
    [CreatedBy]        INT            NOT NULL,
    [Modified]         DATETIME       NULL,
    [ModifiedBy]       INT            NULL,
    [IsDeleted]        BIT            CONSTRAINT [DF__QuoteLine__IsDel__7C6F7215] DEFAULT ((0)) NOT NULL,
    [RoutedToUserID]   INT            NULL,
    [RoutedToGroupID]  INT            NULL,
    [IsPrinted]        BIT            CONSTRAINT [DF_QuoteLines_IsPrinted] DEFAULT ((1)) NULL,
    [LeadTimeDays]     INT            NULL,
    CONSTRAINT [PK__QuoteLin__89C6C92BF93E5ADF] PRIMARY KEY CLUSTERED ([QuoteLineID] ASC)
);


