
CREATE TABLE [dbo].[SearchResults] (
    [ResultID]           INT            IDENTITY (1, 1) NOT NULL,
    [SearchID]           INT            NOT NULL,
    [SearchDetailID]     INT            NULL,
    [ResultType]         CHAR (1)       NOT NULL,
    [DataSource]         VARCHAR (50)   NOT NULL,
    [RecordID]           VARCHAR (50)   NULL,
    [OrderNumber]        NVARCHAR (50)  NULL,
    [OrderDate]          DATE           NULL,
    [OrderStatus]        NVARCHAR (50)  NULL,
    [DueDate]            DATE           NULL,
    [AccountID]          VARCHAR (128)  NULL,
    [AccountName]        VARCHAR (128)  NULL,
    [VendorRating]       INT            NULL,
    [ContactID]          INT            NULL,
    [ContactName]        NVARCHAR (128) NULL,
    [PartNumber]         NVARCHAR (32)  NOT NULL,
    [Manufacturer]       NVARCHAR (128) NULL,
    [Qty]                INT            NULL,
    [ReservedQty]        INT            NULL,
    [AvailableQty]       INT            NULL,
    [ShippedQty]         INT            NULL,
    [TargetPrice]        MONEY          NULL,
    [Price]              MONEY          NULL,
    [Cost]               MONEY          NULL,
    [GrossProfitTotal]   MONEY          NULL,
    [PurchaseOrderID]    INT            NULL,
    [SalesOrderID]       INT            NULL,
    [OwnerName]          NVARCHAR (100) NULL,
    [Buyer]              NVARCHAR (100) NULL,
    [CustomerPartNumber] NVARCHAR (32)  NULL,
    [DateCode]           NVARCHAR (25)  NULL,
    [LeadTimeDays]       INT            NULL,
    [MOQ]                INT            NULL,
    [SPQ]                INT            NULL,
    [Warehouse]          NVARCHAR (50)  NULL,
    [PriceDelta]         MONEY          NULL,
    [Potential]          MONEY          NULL,
    [Company]            NVARCHAR (100) NULL,
    [Note]               NVARCHAR (250) NULL,
    [Created]            DATETIME       CONSTRAINT [DF__SearchRes__Creat__5FF32EF8] DEFAULT (getutcdate()) NOT NULL,
    [CreatedBy]          INT            NOT NULL,
    [WareHouseCode]      VARCHAR (16)   NULL,
    [ReceivedDate]       DATETIME       NULL,
    [ReceivedQty]        INT            NULL,
    [SODate]             DATETIME       NULL,
    [ItemID]             INT            NULL,
    [BOMPartNumber]      VARCHAR (32)   NULL,
    [BOMIntPartNumber]   VARCHAR (32)   NULL,
    [BOMMfg]             VARCHAR (32)   NULL,
    [BOMQty]             VARCHAR (32)   NULL,
    [BOMPrice]           VARCHAR (32)   NULL,
    CONSTRAINT [PK__SearchRe__976902288B431A11] PRIMARY KEY CLUSTERED ([ResultID] ASC)
);


