CREATE TABLE [dbo].[SearchDetails](
	[SearchDetailID] [int] IDENTITY(1,1) NOT NULL,
	[SearchID] [int] NOT NULL,
	[ItemListLineID] [int] NULL,
	[SearchValue] [nvarchar](250) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SearchDetailID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
